import { VideoGames } from './video-games';

export const games: VideoGames[] = [
  {
    id: 0,
    name: 'Stellaris',
    price: 39.99,
    description: 'Become a Galaxy Overlord',
    platform: 'PC',
    genre: 'Real-Time Strategy',
  },
  {
    id: 1,
    name: 'Surviving Mars',
    price: 39.99,
    description: 'Survive onto the Red Planet',
    platform: 'PC',
    genre: 'Real-Time Strategy',
  },
  {
    id: 2,
    name: 'Imperator: ROME',
    price: 39.99,
    description: 'Dominate the Antic World',
    platform: 'PC',
    genre: 'Real-Time Strategy',
  },
  {
    id: 3,
    name: 'Cities Skylines',
    price: 39.99,
    description: 'Become your Dream Mayor as you build your City',
    platform: 'PC',
    genre: 'Real-Time Strategy',
  },
  {
    id: 4,
    name: 'Sea of Thieves',
    price: 39.99,
    description: 'Become the Ruthless Pirate that the Seven Seas has ever seen',
    platform: 'Xbox One',
    genre: 'Action / Aventure',
  },
  {
    id: 5,
    name: 'Gears of War 4',
    price: 39.99,
    description: 'Retake the fight against the Horde',
    platform: 'Xbox One',
    genre: 'Third-Person Shooter',
  },
  {
    id: 6,
    name: 'Horizon: Zero Dawn',
    price: 39.99,
    description: 'Survive to the 31st Earth Post-Apocalyptic Time',
    platform: 'PS4',
    genre: 'Role-Playing Game',
  },
  {
    id: 7,
    name: 'Elite Dangerous',
    price: 39.99,
    description: 'Survive in this Deep Throat Galaxy',
    platform: 'PC',
    genre: 'Space Simulator',
  },
];
